### PR TITLE
Upgrade syntax to terraform 0.12 specs

### PR DESCRIPTION
**Pull request by feraudet**

### CODE REVIEW

**Comment by damaya** [comment]
Hi @feraudet thanks for your contribution and update for the new 0.12 specs

**Review by mauricios — APPROVED** [review]
Looks good to me

**Review by damaya — APPROVED** [review]
Seems to be ok according to the new standard. We'll create a new tag for this, any update/fix will be sent to a new tag.

**Comment by damaya** [comment]
@feraudet the new tag 0.2.0 was released, you can use this release from the registry
https://registry.terraform.io/modules/Aplyca/acm/aws/0.2.0

**Comment by feraudet** [comment]
Cool ! Thank you

**Pull request merged**
